// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ComPortCpuMonitor

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x585555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_image_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Screen1, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Screen1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Screen1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcGPUUsage = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcGPUUsage, 150);
    lv_obj_set_height(ui_ArcGPUUsage, 150);
    lv_obj_set_x(ui_ArcGPUUsage, 2);
    lv_obj_set_y(ui_ArcGPUUsage, 78);
    lv_obj_set_align(ui_ArcGPUUsage, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcGPUUsage, 30);
    lv_obj_set_style_arc_color(ui_ArcGPUUsage, lv_color_hex(0x445379), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcGPUUsage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcGPUUsage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcGPUUsage, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcGPUUsage, lv_color_hex(0x009A17), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcGPUUsage, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ArcCPUUsage = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcCPUUsage, 150);
    lv_obj_set_height(ui_ArcCPUUsage, 150);
    lv_obj_set_x(ui_ArcCPUUsage, 1);
    lv_obj_set_y(ui_ArcCPUUsage, -77);
    lv_obj_set_align(ui_ArcCPUUsage, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcCPUUsage, 50);
    lv_obj_set_style_arc_color(ui_ArcCPUUsage, lv_color_hex(0x3C5C80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcCPUUsage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcCPUUsage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcCPUUsage, lv_color_hex(0xFFB600), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcCPUUsage, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelCPUMem = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelCPUMem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCPUMem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCPUMem, 2);
    lv_obj_set_y(ui_LabelCPUMem, -28);
    lv_obj_set_align(ui_LabelCPUMem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCPUMem, "Cmem");

    ui_LabelGPUMem = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelGPUMem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPUMem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPUMem, 4);
    lv_obj_set_y(ui_LabelGPUMem, 131);
    lv_obj_set_align(ui_LabelGPUMem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPUMem, "Gmem");

    ui_LabelCUPClock = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelCUPClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCUPClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCUPClock, 0);
    lv_obj_set_y(ui_LabelCUPClock, -105);
    lv_obj_set_align(ui_LabelCUPClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCUPClock, "CPU");
    lv_obj_set_style_text_color(ui_LabelCUPClock, lv_color_hex(0x01FFD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCUPClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGPUClock = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelGPUClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPUClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPUClock, 1);
    lv_obj_set_y(ui_LabelGPUClock, 52);
    lv_obj_set_align(ui_LabelGPUClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPUClock, "GPU");
    lv_obj_set_style_text_color(ui_LabelGPUClock, lv_color_hex(0xFF9797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGPUClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCPUtemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelCPUtemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCPUtemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCPUtemp, 0);
    lv_obj_set_y(ui_LabelCPUtemp, -69);
    lv_obj_set_align(ui_LabelCPUtemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCPUtemp, "CTemp");
    lv_obj_set_style_text_color(ui_LabelCPUtemp, lv_color_hex(0xF4AE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCPUtemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGPUTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelGPUTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPUTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPUTemp, 1);
    lv_obj_set_y(ui_LabelGPUTemp, 90);
    lv_obj_set_align(ui_LabelGPUTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPUTemp, "GTemp");
    lv_obj_set_style_text_color(ui_LabelGPUTemp, lv_color_hex(0x00CD1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGPUTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCPUFan = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelCPUFan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCPUFan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCPUFan, 37);
    lv_obj_set_y(ui_LabelCPUFan, -154);
    lv_obj_set_align(ui_LabelCPUFan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCPUFan, "CFan");
    lv_obj_set_style_text_color(ui_LabelCPUFan, lv_color_hex(0xFA7300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCPUFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGPUFan = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelGPUFan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPUFan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPUFan, 9);
    lv_obj_set_y(ui_LabelGPUFan, 152);
    lv_obj_set_align(ui_LabelGPUFan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPUFan, "GFan");
    lv_obj_add_flag(ui_LabelGPUFan, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelGPUFan, lv_color_hex(0xD4650B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGPUFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCore = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelCore, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCore, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCore, -60);
    lv_obj_set_y(ui_LabelCore, -3);
    lv_obj_set_align(ui_LabelCore, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCore, "Cores");
    lv_obj_add_flag(ui_LabelCore, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_cpu_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -69);
    lv_obj_set_y(ui_Image2, -143);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 15);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_885004004);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -69);
    lv_obj_set_y(ui_Image3, 6);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 23);

    ui_arc_gpu = ui_ArcGPUUsage;
    ui_arc_cpu = ui_ArcCPUUsage;
    ui_label_mem = ui_LabelCPUMem;
    ui_label_gpumem = ui_LabelGPUMem;
    ui_label_cpuclock = ui_LabelCUPClock;
    ui_label_gpuclock = ui_LabelGPUClock;
    ui_label_cputemp = ui_LabelCPUtemp;
    ui_label_gputemp = ui_LabelGPUTemp;
    ui_label_cpufan = ui_LabelCPUFan;
    ui_label_gpufan = ui_LabelGPUFan;
    ui_label_cpucores = ui_LabelCore;

}
