// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ComPortCpuMonitor

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_ArcGPUUsage;
lv_obj_t * ui_ArcCPUUsage;
lv_obj_t * ui_LabelCPUMem;
lv_obj_t * ui_LabelGPUMem;
lv_obj_t * ui_LabelCUPClock;
lv_obj_t * ui_LabelGPUClock;
lv_obj_t * ui_LabelCPUtemp;
lv_obj_t * ui_LabelGPUTemp;
lv_obj_t * ui_LabelCPUFan;
lv_obj_t * ui_LabelGPUFan;
lv_obj_t * ui_LabelCore;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES
lv_obj_t * ui_arc_gpu;
lv_obj_t * ui_arc_cpu;
lv_obj_t * ui_label_mem;
lv_obj_t * ui_label_gpumem;
lv_obj_t * ui_label_cpuclock;
lv_obj_t * ui_label_gpuclock;
lv_obj_t * ui_label_cputemp;
lv_obj_t * ui_label_gputemp;
lv_obj_t * ui_label_cpufan;
lv_obj_t * ui_label_gpufan;
lv_obj_t * ui_label_cpucores;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
