// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: ComPortCpuMonitor

#ifndef _COMPORTCPUMONITOR_UI_H
#define _COMPORTCPUMONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ArcGPUUsage;
extern lv_obj_t * ui_ArcCPUUsage;
extern lv_obj_t * ui_LabelCPUMem;
extern lv_obj_t * ui_LabelGPUMem;
extern lv_obj_t * ui_LabelCUPClock;
extern lv_obj_t * ui_LabelGPUClock;
extern lv_obj_t * ui_LabelCPUtemp;
extern lv_obj_t * ui_LabelGPUTemp;
extern lv_obj_t * ui_LabelCPUFan;
extern lv_obj_t * ui_LabelGPUFan;
extern lv_obj_t * ui_LabelCore;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES
extern lv_obj_t * ui_arc_gpu;
extern lv_obj_t * ui_arc_cpu;
extern lv_obj_t * ui_label_mem;
extern lv_obj_t * ui_label_gpumem;
extern lv_obj_t * ui_label_cpuclock;
extern lv_obj_t * ui_label_gpuclock;
extern lv_obj_t * ui_label_cputemp;
extern lv_obj_t * ui_label_gputemp;
extern lv_obj_t * ui_label_cpufan;
extern lv_obj_t * ui_label_gpufan;
extern lv_obj_t * ui_label_cpucores;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_image_png);    // assets/image.png
LV_IMG_DECLARE(ui_img_cpu_png);    // assets/cpu.png
LV_IMG_DECLARE(ui_img_885004004);    // assets/graphic-card.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
